# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freedback.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='freedback.proto',
  package='freedback',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x66reedback.proto\x12\tfreedback\"\x81\x01\n\x05\x45ntry\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12#\n\x07\x63omment\x18\x02 \x01(\x0b\x32\x12.freedback.Comment\x12!\n\x06rating\x18\x03 \x01(\x0b\x32\x11.freedback.Rating\x12\x1f\n\x05issue\x18\x04 \x01(\x0b\x32\x10.freedback.Issue\"2\n\x0b\x45ntryAccess\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x16\n\x0e\x61uthentication\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x17\n\x07\x43omment\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\x06Rating\x12\r\n\x05value\x18\x01 \x01(\r\x12\x0f\n\x07\x64ivisor\x18\x02 \x01(\r\"\x15\n\x05Issue\x12\x0c\n\x04text\x18\x01 \x01(\t2v\n\x08Receiver\x12\x34\n\x06submit\x12\x10.freedback.Entry\x1a\x16.freedback.EntryAccess\"\x00\x12\x34\n\x06\x64\x65lete\x12\x16.freedback.EntryAccess\x1a\x10.freedback.Empty\"\x00\x42\x39\n\x15io.freedack.prototypeB\x12\x46reedbackPrototypeP\x01\xa2\x02\tFreedbackb\x06proto3')
)




_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='freedback.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='freedback.Entry.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment', full_name='freedback.Entry.comment', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rating', full_name='freedback.Entry.rating', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='issue', full_name='freedback.Entry.issue', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=160,
)


_ENTRYACCESS = _descriptor.Descriptor(
  name='EntryAccess',
  full_name='freedback.EntryAccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='freedback.EntryAccess.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authentication', full_name='freedback.EntryAccess.authentication', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=212,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='freedback.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=221,
)


_COMMENT = _descriptor.Descriptor(
  name='Comment',
  full_name='freedback.Comment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='freedback.Comment.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=246,
)


_RATING = _descriptor.Descriptor(
  name='Rating',
  full_name='freedback.Rating',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='freedback.Rating.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='divisor', full_name='freedback.Rating.divisor', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=288,
)


_ISSUE = _descriptor.Descriptor(
  name='Issue',
  full_name='freedback.Issue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='freedback.Issue.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=311,
)

_ENTRY.fields_by_name['comment'].message_type = _COMMENT
_ENTRY.fields_by_name['rating'].message_type = _RATING
_ENTRY.fields_by_name['issue'].message_type = _ISSUE
DESCRIPTOR.message_types_by_name['Entry'] = _ENTRY
DESCRIPTOR.message_types_by_name['EntryAccess'] = _ENTRYACCESS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Comment'] = _COMMENT
DESCRIPTOR.message_types_by_name['Rating'] = _RATING
DESCRIPTOR.message_types_by_name['Issue'] = _ISSUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
  DESCRIPTOR = _ENTRY,
  __module__ = 'freedback_pb2'
  # @@protoc_insertion_point(class_scope:freedback.Entry)
  ))
_sym_db.RegisterMessage(Entry)

EntryAccess = _reflection.GeneratedProtocolMessageType('EntryAccess', (_message.Message,), dict(
  DESCRIPTOR = _ENTRYACCESS,
  __module__ = 'freedback_pb2'
  # @@protoc_insertion_point(class_scope:freedback.EntryAccess)
  ))
_sym_db.RegisterMessage(EntryAccess)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'freedback_pb2'
  # @@protoc_insertion_point(class_scope:freedback.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Comment = _reflection.GeneratedProtocolMessageType('Comment', (_message.Message,), dict(
  DESCRIPTOR = _COMMENT,
  __module__ = 'freedback_pb2'
  # @@protoc_insertion_point(class_scope:freedback.Comment)
  ))
_sym_db.RegisterMessage(Comment)

Rating = _reflection.GeneratedProtocolMessageType('Rating', (_message.Message,), dict(
  DESCRIPTOR = _RATING,
  __module__ = 'freedback_pb2'
  # @@protoc_insertion_point(class_scope:freedback.Rating)
  ))
_sym_db.RegisterMessage(Rating)

Issue = _reflection.GeneratedProtocolMessageType('Issue', (_message.Message,), dict(
  DESCRIPTOR = _ISSUE,
  __module__ = 'freedback_pb2'
  # @@protoc_insertion_point(class_scope:freedback.Issue)
  ))
_sym_db.RegisterMessage(Issue)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025io.freedack.prototypeB\022FreedbackPrototypeP\001\242\002\tFreedback'))

_RECEIVER = _descriptor.ServiceDescriptor(
  name='Receiver',
  full_name='freedback.Receiver',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=313,
  serialized_end=431,
  methods=[
  _descriptor.MethodDescriptor(
    name='submit',
    full_name='freedback.Receiver.submit',
    index=0,
    containing_service=None,
    input_type=_ENTRY,
    output_type=_ENTRYACCESS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='freedback.Receiver.delete',
    index=1,
    containing_service=None,
    input_type=_ENTRYACCESS,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECEIVER)

DESCRIPTOR.services_by_name['Receiver'] = _RECEIVER

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ReceiverStub(object):
    """Service with an endpoint to receive freedback entries.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.submit = channel.unary_unary(
          '/freedback.Receiver/submit',
          request_serializer=Entry.SerializeToString,
          response_deserializer=EntryAccess.FromString,
          )
      self.delete = channel.unary_unary(
          '/freedback.Receiver/delete',
          request_serializer=EntryAccess.SerializeToString,
          response_deserializer=Empty.FromString,
          )


  class ReceiverServicer(object):
    """Service with an endpoint to receive freedback entries.
    """

    def submit(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'submit': grpc.unary_unary_rpc_method_handler(
            servicer.submit,
            request_deserializer=Entry.FromString,
            response_serializer=EntryAccess.SerializeToString,
        ),
        'delete': grpc.unary_unary_rpc_method_handler(
            servicer.delete,
            request_deserializer=EntryAccess.FromString,
            response_serializer=Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'freedback.Receiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaReceiverServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """Service with an endpoint to receive freedback entries.
    """
    def submit(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def delete(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaReceiverStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """Service with an endpoint to receive freedback entries.
    """
    def submit(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    submit.future = None
    def delete(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    delete.future = None


  def beta_create_Receiver_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('freedback.Receiver', 'delete'): EntryAccess.FromString,
      ('freedback.Receiver', 'submit'): Entry.FromString,
    }
    response_serializers = {
      ('freedback.Receiver', 'delete'): Empty.SerializeToString,
      ('freedback.Receiver', 'submit'): EntryAccess.SerializeToString,
    }
    method_implementations = {
      ('freedback.Receiver', 'delete'): face_utilities.unary_unary_inline(servicer.delete),
      ('freedback.Receiver', 'submit'): face_utilities.unary_unary_inline(servicer.submit),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Receiver_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('freedback.Receiver', 'delete'): EntryAccess.SerializeToString,
      ('freedback.Receiver', 'submit'): Entry.SerializeToString,
    }
    response_deserializers = {
      ('freedback.Receiver', 'delete'): Empty.FromString,
      ('freedback.Receiver', 'submit'): EntryAccess.FromString,
    }
    cardinalities = {
      'delete': cardinality.Cardinality.UNARY_UNARY,
      'submit': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'freedback.Receiver', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
